import { Tournament, User, LeaderboardUser, Announcement, MatchRegistration, Transaction } from '../types';

export const INITIAL_USER: User = {
  id: 'usr_1',
  name: 'Rahul "ProBooyah" Sharma',
  email: 'probooyah@freefire.com',
  phone: '+91 98765 43210',
  ffIgn: 'Viper_Booyah99',
  ffUid: '8273910481',
  avatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150&auto=format&fit=crop&q=80',
  character: 'Alok',
  walletBalance: 450,
  bonusCoins: 120,
  level: 68,
  rank: 'Heroic',
  role: 'player',
  stats: {
    matchesPlayed: 42,
    totalWins: 18,
    totalKills: 164,
    totalWinnings: 2850,
  },
  referralCode: 'BOOYAH99',
  referredCount: 7,
};

export const ADMIN_USER: User = {
  id: 'usr_admin',
  name: 'Esports Tournament Admin',
  email: 'admin@freefire.com',
  phone: '+91 90000 00000',
  ffIgn: 'FF_OFFICIAL_HOST',
  ffUid: '1000000000',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  character: 'Chrono',
  walletBalance: 99999,
  bonusCoins: 50000,
  level: 100,
  rank: 'Grandmaster',
  role: 'admin',
  stats: {
    matchesPlayed: 120,
    totalWins: 90,
    totalKills: 850,
    totalWinnings: 50000,
  },
  referralCode: 'FFADMIN',
  referredCount: 150,
};

export const INITIAL_TOURNAMENTS: Tournament[] = [
  {
    id: 'tr_101',
    title: '🔥 Bermuda Daily Solo Showdown #402',
    subtitle: 'High Kill Reward - Solo Battle Royale',
    mode: 'Solo',
    map: 'Bermuda',
    type: 'Battle Royale',
    entryFee: 30,
    prizePool: 1200,
    perKillReward: 15,
    firstPrize: 400,
    secondPrize: 200,
    thirdPrize: 100,
    totalSlots: 48,
    filledSlots: 38,
    startTime: new Date(Date.now() + 35 * 60 * 1000).toISOString(), // 35 mins from now
    status: 'Joining Open',
    roomId: '8829104',
    roomPassword: 'FF88',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80',
    badge: 'TOP FEATURED',
    organizer: 'Garena Official Host',
    rules: [
      'Emulators strictly not allowed (Mobile devices only).',
      'Room ID and Password will be provided 15 minutes before start.',
      'Take a screenshot of the Booyah / Kill summary screen for result validation.',
      'Teaming up or hacking will lead to immediate ban and loss of entry fee.',
    ],
  },
  {
    id: 'tr_102',
    title: '⚡ Clash Squad 4v4 Duo Cup (Ranked)',
    subtitle: '7 Rounds - Fast Paced CS Knockout',
    mode: 'Clash Squad',
    map: 'Kalahari',
    type: 'Clash Squad 4v4',
    entryFee: 50,
    prizePool: 2000,
    perKillReward: 0,
    firstPrize: 1200,
    secondPrize: 800,
    thirdPrize: 0,
    totalSlots: 16,
    filledSlots: 14,
    startTime: new Date(Date.now() + 110 * 60 * 1000).toISOString(),
    status: 'Joining Open',
    image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&auto=format&fit=crop&q=80',
    badge: 'CS 4v4 KNOCKOUT',
    organizer: 'Booyah Esports',
    rules: [
      'Character Skills Allowed: Alok, Chrono, K, Tatsuya.',
      'No Grenade spam in round 1.',
      'Best of 7 rounds format.',
      'Opponents must be ready 5 minutes before match time.',
    ],
  },
  {
    id: 'tr_103',
    title: '🎁 Weekend FREE ENTRY Grand Battle Royale',
    subtitle: 'Zero Fee - Pure Cash Prizes for Everyone!',
    mode: 'Solo',
    map: 'Purgatory',
    type: 'Battle Royale',
    entryFee: 0,
    prizePool: 500,
    perKillReward: 5,
    firstPrize: 200,
    secondPrize: 100,
    thirdPrize: 50,
    totalSlots: 48,
    filledSlots: 48,
    startTime: new Date(Date.now() + 15 * 60 * 1000).toISOString(), // 15 mins
    status: 'Room Full',
    roomId: '7721094',
    roomPassword: 'BOOYAH2026',
    image: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=800&auto=format&fit=crop&q=80',
    badge: '100% FREE ENTRY',
    organizer: 'Community Arena',
    rules: [
      'Open to all players level 20+.',
      'Free entry tournament limit 1 per user per day.',
      'Fair play detection active.',
    ],
  },
  {
    id: 'tr_104',
    title: '🏆 Grand Squad Championship (Bermuda & Purgatory)',
    subtitle: 'High Stakes 4-Man Squad Deathmatch',
    mode: 'Squad',
    map: 'Bermuda',
    type: 'Battle Royale',
    entryFee: 120,
    prizePool: 5000,
    perKillReward: 30,
    firstPrize: 2500,
    secondPrize: 1500,
    thirdPrize: 1000,
    totalSlots: 12,
    filledSlots: 7,
    startTime: new Date(Date.now() + 240 * 60 * 1000).toISOString(),
    status: 'Joining Open',
    image: 'https://images.unsplash.com/photo-1560253023-3ec5d502959f?w=800&auto=format&fit=crop&q=80',
    badge: 'MEGA PRIZE POOL',
    organizer: 'Garena India League',
    rules: [
      'Full squad required at time of registration.',
      '2 Maps (Bermuda + Purgatory points accumulation).',
      'Custom room created by official referee.',
    ],
  },
  {
    id: 'tr_105',
    title: '🎯 Nexterra Sniper Battle (Solo Only)',
    subtitle: 'Sniper Rifles Only - AWM & M82B',
    mode: 'Solo',
    map: 'Nexterra',
    type: 'Battle Royale',
    entryFee: 20,
    prizePool: 800,
    perKillReward: 12,
    firstPrize: 300,
    secondPrize: 150,
    thirdPrize: 70,
    totalSlots: 48,
    filledSlots: 22,
    startTime: new Date(Date.now() + 320 * 60 * 1000).toISOString(),
    status: 'Joining Open',
    image: 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?w=800&auto=format&fit=crop&q=80',
    badge: 'SNIPER MODE',
    organizer: 'Sniper Kings',
    rules: [
      'Only Sniper Rifles allowed.',
      'Melee weapons permitted.',
    ],
  },
  {
    id: 'tr_106',
    title: '⚔️ Alpine Duo Deathmatch #12',
    subtitle: 'Survive with your partner to claim Booyah',
    mode: 'Duo',
    map: 'Alpine',
    type: 'Battle Royale',
    entryFee: 40,
    prizePool: 1500,
    perKillReward: 20,
    firstPrize: 700,
    secondPrize: 400,
    thirdPrize: 200,
    totalSlots: 24,
    filledSlots: 24,
    startTime: new Date(Date.now() - 45 * 60 * 1000).toISOString(), // Past match
    status: 'Completed',
    roomId: '6610293',
    roomPassword: 'ALPINEPASS',
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80',
    badge: 'COMPLETED',
    organizer: 'Free Fire Premier',
    rules: ['Duo match rules apply.'],
  }
];

export const INITIAL_REGISTRATIONS: MatchRegistration[] = [
  {
    id: 'reg_101',
    tournamentId: 'tr_101',
    userId: 'usr_1',
    userIgn: 'Viper_Booyah99',
    userUid: '8273910481',
    slotNumber: 12,
    registeredAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    status: 'Confirmed',
    resultStatus: 'None',
  },
  {
    id: 'reg_106',
    tournamentId: 'tr_106',
    userId: 'usr_1',
    userIgn: 'Viper_Booyah99',
    userUid: '8273910481',
    slotNumber: 4,
    registeredAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    status: 'Confirmed',
    killsSubmitted: 8,
    placementSubmitted: 1,
    prizeWon: 860, // First prize + kills
    resultStatus: 'Approved',
    adminNote: 'Verified Booyah screenshot! Excellent gameplay.',
  }
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'txn_201',
    userId: 'usr_1',
    type: 'Winning Credit',
    amount: 860,
    status: 'Success',
    timestamp: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    description: 'Booyah + 8 Kills Bonus for Alpine Duo Deathmatch #12',
    referenceId: 'tr_106',
  },
  {
    id: 'txn_202',
    userId: 'usr_1',
    type: 'Tournament Entry',
    amount: 30,
    status: 'Success',
    timestamp: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
    description: 'Entry fee for Bermuda Daily Solo Showdown #402',
    referenceId: 'tr_101',
  },
  {
    id: 'txn_203',
    userId: 'usr_1',
    type: 'Deposit',
    amount: 200,
    status: 'Success',
    timestamp: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    description: 'UPI Add Money (Ref: UPI/901823901)',
  },
  {
    id: 'txn_204',
    userId: 'usr_1',
    type: 'Referral Bonus',
    amount: 50,
    status: 'Success',
    timestamp: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    description: 'Referral code reward (Friend: FF_Rider_07)',
  }
];

export const INITIAL_LEADERBOARD: LeaderboardUser[] = [
  {
    rank: 1,
    userId: 'lb_1',
    name: 'Aman "ApexKill" Verma',
    ffIgn: 'APEX_GOD_99',
    ffUid: '7729104810',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    kills: 412,
    wins: 58,
    winnings: 14500,
    rankTier: 'Grandmaster',
  },
  {
    rank: 2,
    userId: 'lb_2',
    name: 'Karan "ToxicSniper" Singh',
    ffIgn: 'Toxic_Headshot',
    ffUid: '6610293812',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    kills: 380,
    wins: 49,
    winnings: 11200,
    rankTier: 'Grandmaster',
  },
  {
    rank: 3,
    userId: 'lb_3',
    name: 'Priya "QueenBooyah" Patel',
    ffIgn: 'Queen_Priya_FF',
    ffUid: '9910283719',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    kills: 325,
    wins: 41,
    winnings: 9800,
    rankTier: 'Grandmaster',
  },
  {
    rank: 4,
    userId: 'usr_1',
    name: 'Rahul "ProBooyah" Sharma',
    ffIgn: 'Viper_Booyah99',
    ffUid: '8273910481',
    avatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150&auto=format&fit=crop&q=80',
    kills: 164,
    wins: 18,
    winnings: 2850,
    rankTier: 'Heroic',
  },
  {
    rank: 5,
    userId: 'lb_5',
    name: 'Vikram "ShadowRider" Rao',
    ffIgn: 'Shadow_Ninja_X',
    ffUid: '5519283019',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    kills: 142,
    wins: 15,
    winnings: 2100,
    rankTier: 'Heroic',
  },
  {
    rank: 6,
    userId: 'lb_6',
    name: 'Suresh "GhostHunter"',
    ffIgn: 'Ghost_Hunter_007',
    ffUid: '4410293811',
    avatar: 'https://images.unsplash.com/photo-1628157582853-a796fa650a6a?w=150&auto=format&fit=crop&q=80',
    kills: 118,
    wins: 11,
    winnings: 1650,
    rankTier: 'Diamond',
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'anc_1',
    title: '🔥 Grand Weekly ₹10,000 Free Fire Cup Announced!',
    content: 'Registration opens this Friday at 6:00 PM IST. Get your squad ready!',
    badge: 'NEW CUP',
    date: 'July 24, 2026',
    image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'anc_2',
    title: '⚡ Instant Auto Cashout via UPI Active',
    content: 'All withdrawal requests under ₹1,000 are now processed instantly within 5 minutes.',
    badge: 'WALLETS',
    date: 'July 23, 2026',
  },
  {
    id: 'anc_3',
    title: '🎁 50% Bonus Coins on First Deposit!',
    content: 'Use code "BOOYAH50" while topping up ₹100 or more to get extra 50 bonus coins.',
    badge: 'PROMO CODE',
    date: 'July 22, 2026',
  }
];

export const FREE_FIRE_CHARACTERS = [
  { name: 'Alok', icon: '🎧', power: 'Drop The Beat (Speed & HP Aura)' },
  { name: 'Chrono', icon: '🛡️', power: 'Time Turner (Force Field Shield)' },
  { name: 'Tatsuya', icon: '⚡', power: 'Rebel Rush (Instant Dash)' },
  { name: 'K (Captain Booyah)', icon: '🥋', power: 'Master of All (EP Boost)' },
  { name: 'Kelly', icon: '🏃‍♀️', power: 'Dash (Sprinting Speed)' },
  { name: 'Hayato', icon: '⚔️', power: 'Bushido (Armor Penetration)' },
];
